name: Run Serivicio A
on:
  pull_request:
    paths:
      - 'servicio-A/**'
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: servicio-A

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: list files
        run: ls

      - name: Install Dependencies
        run: npm install
        
      - name: Run index
        run: node index.js
